# Generated by Django 2.1.7 on 2019-02-21 16:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Author', '0002_auto_20190221_1645'),
        ('Posts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('comment_id', models.AutoField(primary_key=True, serialize=False)),
                ('comment', models.TextField()),
                ('published', models.DateTimeField(verbose_name='date published')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Author.Author')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('img_id', models.AutoField(primary_key=True, serialize=False)),
                ('compressed_img', models.TextField(null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='post',
            name='visibility',
        ),
        migrations.AddField(
            model_name='post',
            name='permission',
            field=models.CharField(choices=[('M', 'me'), ('L', 'permitted authors'), ('F', 'my friends'), ('FF', 'friends of friends'), ('FH', 'friends on my host'), ('P', 'public')], default='P', max_length=2),
        ),
        migrations.AddField(
            model_name='post',
            name='permitted_authors',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Author.Author'),
        ),
        migrations.AddField(
            model_name='image',
            name='post_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Posts.Post'),
        ),
        migrations.AddField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Posts.Post'),
        ),
    ]
