# Generated by Django 2.1.7 on 2019-02-20 21:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Author', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('post_id', models.AutoField(primary_key=True, serialize=False)),
                ('publicationDate', models.DateTimeField(verbose_name='date published')),
                ('content', models.TextField()),
                ('title', models.CharField(max_length=50)),
                ('visibility', models.CharField(max_length=50)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Author.Author')),
            ],
        ),
    ]
