# Generated by Django 2.1.7 on 2019-02-21 16:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Author', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='githubUrl',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='author',
            name='hostName',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='friendrequest',
            name='from_author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='friend_request_sent', to='Author.Author'),
        ),
        migrations.AlterField(
            model_name='friendrequest',
            name='to_author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='friend_request_recieved', to='Author.Author'),
        ),
        migrations.AlterField(
            model_name='friends',
            name='author1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='friend1', to='Author.Author'),
        ),
        migrations.AlterField(
            model_name='friends',
            name='author2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='friend2', to='Author.Author'),
        ),
    ]
